query Slide {
  slide(where: { id: "cl0f09v9f2avl0b13idvxmx4b" }) {
    id
    slide(where: { id: "cl0f092z62atz0b13j9m5etvh" }) {
      id
      url
    }
  }
}

query Slides {
  slides {
    id
    slide {
      id
      url(
        transformation: {
          image: {
            resize: { fit: clip, height: 900, width: 1600 }
          }
        }
      )
    }
  }
}

query Assets($OR: [AssetWhereInput!]) {
  assets(where: { OR: $OR }) {
    id
    fileName
    url
  }
}
