query AllTodos {
  allTodos {
    data {
      _id
      task
      completed
    }
  }
}

mutation CreateTodo($data: TodoInput!) {
  createTodo(data: $data) {
    _id
    task
    completed
  }
}

mutation PartialUpdateTodo(
  $id: ID!
  $data: PartialUpdateTodoInput!
) {
  partialUpdateTodo(id: $id, data: $data) {
    _id
    task
    completed
  }
}

mutation DeleteTodo($id: ID!) {
  deleteTodo(id: $id) {
    _id
  }
}
